version: 2.1

defaults: &defaults
  working_directory: /go/src/github.com/interchainio/tm-load-test
  docker:
    - image: circleci/golang

jobs:
  lint:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Lint
          command: |
            make lint
  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Test
          command: |
            make test
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Build
          command: |
            make build
      - persist_to_workspace:
          root: build
          paths:
            - "*"
  release:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /go/src/github.com/interchainio/tm-load-test/build
      - run:
          name: Release
          command: |
            /bin/bash .circleci/release.bash

workflows:
  version: 2

# Note: mini_qa disabled as per Thane's request
#  mini_qa:
#    jobs:
#      - lint
#      - test
#      - build
  release_management:
    jobs:
      - lint:
          filters:
            branches:
              only:
                - develop
                - master
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+/
      - test:
          filters:
            branches:
              only:
                - develop
                - master
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+/
      - build:
          requires:
            - lint
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+/
      - release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+/
